/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.disenosoft.universidad.vista.gui;

import java.util.List;

import javax.swing.table.DefaultTableModel;

import co.edu.eam.disenosoft.universidad.vista.controladores.ControladorDialogoVerEstudiante;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.Estudiante;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.Nota;

/**
 *
 * @author user
 */
public class DialogoVerEstudiante extends javax.swing.JDialog {

	private Estudiante est;
	private ControladorDialogoVerEstudiante controlador;

	/**
	 * Creates new form DialogoVerEstudiante
	 */
	public DialogoVerEstudiante(Estudiante e) {
		super();
		controlador = new ControladorDialogoVerEstudiante();
		initComponents();
		est = e;
		refrescarTabla();
		mensaje();
		calcularDefinitiva();
		setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel2 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		tfcedulaestudiante = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		tfnombreestudiante = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		tfcreditosregistradosestudiante = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		tablaNotas = new javax.swing.JTable();
		jLabel1 = new javax.swing.JLabel();
		lblDefinitiva = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Notas Curso Estudiante");
		setModal(true);
		setResizable(false);

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Estudiante"));

		jLabel3.setText("Cedula");

		tfcedulaestudiante.setEditable(false);

		jLabel4.setText("Nombre");

		tfnombreestudiante.setEditable(false);

		jLabel6.setText("Creditos Registrados");

		tfcreditosregistradosestudiante.setEditable(false);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel6).addComponent(jLabel4).addComponent(jLabel3))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(tfnombreestudiante).addComponent(tfcedulaestudiante)
								.addComponent(tfcreditosregistradosestudiante))
						.addContainerGap()));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3).addComponent(tfcedulaestudiante,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(5, 5, 5)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel4).addComponent(tfnombreestudiante,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(tfcreditosregistradosestudiante, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel6))
						.addContainerGap(14, Short.MAX_VALUE)));

		tablaNotas
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null }, { null, null, null }, { null, null, null },
								{ null, null, null } },
						new String[] { "Evaluacion", "Callificacion", "Porcentaje(%)" }));
		jScrollPane1.setViewportView(tablaNotas);

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jLabel1.setText("Definitiva:");

		lblDefinitiva.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		lblDefinitiva.setText("0");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addContainerGap(15, Short.MAX_VALUE).addComponent(jLabel1)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(lblDefinitiva).addGap(268, 268, 268))
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1).addComponent(lblDefinitiva))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void calcularDefinitiva (){
		try {
			List<Nota> notas = controlador.notasEstudiante(est);
			double definitiva = controlador.calcularDefinitva(notas);
			lblDefinitiva.setText(definitiva+"");
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}
	
	private void mensaje() {
		try {
			tfcedulaestudiante.setText(est.getCedula());
			tfnombreestudiante.setText(est.getNombre());
			int creditos = controlador.creditosEstudiante(est);
			tfcreditosregistradosestudiante.setText(creditos + "");
			
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void refrescarTabla() {
		try {
			DefaultTableModel dtm = (DefaultTableModel) tablaNotas.getModel();
			dtm.setRowCount(0);
			List<Nota> notas = controlador.notasEstudiante(est);
			for (Nota lista : notas) {
				dtm.addRow(new Object[] { lista.getEvaluacion().getNombre(), lista.getValor(),
						lista.getEvaluacion().getPorcentaje() });
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lblDefinitiva;
	private javax.swing.JTable tablaNotas;
	private javax.swing.JTextField tfcedulaestudiante;
	private javax.swing.JTextField tfcreditosregistradosestudiante;
	private javax.swing.JTextField tfnombreestudiante;
	// End of variables declaration//GEN-END:variables
}
