/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.disenosoft.universidad.vista.gui;

import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import co.edu.eam.disenosoft.universidad.modelo.enumeraciones.DiaEnum;
import co.edu.eam.disenosoft.universidad.vista.controladores.ControladorAdministrarCurso;
import co.edu.eam.ingesoft.desarrollo.logica.excepcion.ExcepcionNegocio;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.Asignatura;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.Curso;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.Profesor;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.SesionCurso;

/**
 *
 * @author dir_software
 */
public class VentanaCrearCurso extends javax.swing.JInternalFrame {

	private ControladorAdministrarCurso adminCurso;
	private Asignatura asigBuscada;
	private Curso cursoActual;
	private Profesor docenteEcontrado;

	/**
	 * Creates new form VentanaCrearCurso
	 */
	public VentanaCrearCurso() {
		adminCurso = new ControladorAdministrarCurso();
		asigBuscada = null;
		cursoActual = null;
		docenteEcontrado = null;
		initComponents();
		llenarComboDia();
		setClosable(true);
		setVisible(true);
		setMaximizable(false);
		setIconifiable(true);
		setResizable(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		tfcodigoasignatura = new javax.swing.JTextField();
		btnBuscarAsignatura = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		tfnombreasignatura = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		tfceduladocente = new javax.swing.JTextField();
		btnBuscarDocente = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		tfnombredocente = new javax.swing.JTextField();
		jPanel3 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		comboDia = new javax.swing.JComboBox();
		jLabel6 = new javax.swing.JLabel();
		comboHoraInicio = new javax.swing.JComboBox();
		comboHoraFin = new javax.swing.JComboBox();
		jLabel7 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tablaHorario = new javax.swing.JTable();
		btnAgregarSesion = new javax.swing.JButton();
		btnQuitarSesion = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		btnCrear = new javax.swing.JButton();
		btnBuscar = new javax.swing.JButton();
		brtnEditar = new javax.swing.JButton();
		jTFCodigoCurso = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();

		setTitle("Administrar Curso");
		setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/class.png"))); // NOI18N

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Asignatura"));

		jLabel1.setText("Codigo");

		btnBuscarAsignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
		btnBuscarAsignatura.setToolTipText("Buscar Asignatura");
		btnBuscarAsignatura.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBuscarAsignaturaActionPerformed(evt);
			}
		});

		jLabel2.setText("Nombre");

		tfnombreasignatura.setEditable(false);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(23, 23, 23)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel1).addComponent(jLabel2))
						.addGap(49, 49, 49)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(tfcodigoasignatura).addComponent(tfnombreasignatura))
						.addGap(18, 18, 18).addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE,
								77, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(53, 53, 53)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(16, 16, 16).addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel1).addComponent(tfcodigoasignatura,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel2).addComponent(tfnombreasignatura,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Docente"));

		jLabel3.setText("Cedula");

		btnBuscarDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
		btnBuscarDocente.setToolTipText("Buscar Docente");
		btnBuscarDocente.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBuscarDocenteActionPerformed(evt);
			}
		});

		jLabel4.setText("Nombre");

		tfnombredocente.setEditable(false);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(23, 23, 23)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel3).addComponent(jLabel4))
						.addGap(49, 49, 49)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(tfceduladocente).addComponent(tfnombredocente))
						.addGap(18, 18, 18).addComponent(btnBuscarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 77,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(53, 53, 53)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(16, 16, 16).addGroup(jPanel2Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addComponent(btnBuscarDocente, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel3).addComponent(tfceduladocente,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel4).addComponent(tfnombredocente,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Horario Asignatura"));

		jLabel5.setText("Dia");

		jLabel6.setText("Hora Inicio:");

		comboHoraInicio.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "7", "8", "9", "10", "13", "14", "15", "16", "17", "18", "19", "20" }));

		comboHoraFin.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22" }));

		jLabel7.setText("Hora Fin:");

		tablaHorario.setModel(new javax.swing.table.DefaultTableModel(new Object[][] { { null, null, null },
				{ null, null, null }, { null, null, null }, { null, null, null } },
				new String[] { "Dia", "Hora Inicial", "Hora Final" }));
		jScrollPane1.setViewportView(tablaHorario);

		btnAgregarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculation1.png"))); // NOI18N
		btnAgregarSesion.setToolTipText("Agregar sesion");
		btnAgregarSesion.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAgregarSesionActionPerformed(evt);
			}
		});

		btnQuitarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculation.png"))); // NOI18N
		btnQuitarSesion.setToolTipText("Quitar Sesion");
		btnQuitarSesion.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnQuitarSesionActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap().addGroup(jPanel3Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel3Layout.createSequentialGroup()
								.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel5).addComponent(jLabel6))
								.addGap(18, 18, 18)
								.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
										false)
										.addGroup(jPanel3Layout.createSequentialGroup()
												.addComponent(comboHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE,
														87, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(comboHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(comboDia, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE))
								.addGap(18, 18, 18).addComponent(btnAgregarSesion,
										javax.swing.GroupLayout.PREFERRED_SIZE, 72,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(btnQuitarSesion))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel3Layout
				.setVerticalGroup(
						jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel3Layout.createSequentialGroup()
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addGroup(jPanel3Layout.createSequentialGroup()
														.addGroup(jPanel3Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(jLabel5).addComponent(comboDia,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(jPanel3Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(jLabel6)
																.addComponent(comboHoraInicio,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jLabel7).addComponent(comboHoraFin,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(jPanel3Layout.createSequentialGroup().addGap(1, 1, 1)
														.addComponent(btnAgregarSesion,
																javax.swing.GroupLayout.DEFAULT_SIZE, 49,
																Short.MAX_VALUE)))
										.addGap(18, 18, 18)
										.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(btnQuitarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 21,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(77, 77, 77)));

		jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculation1.png"))); // NOI18N
		btnCrear.setToolTipText("Crear");
		btnCrear.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCrearActionPerformed(evt);
			}
		});

		btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
		btnBuscar.setToolTipText("Buscar");
		btnBuscar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBuscarActionPerformed(evt);
			}
		});

		brtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pen38.png"))); // NOI18N
		brtnEditar.setToolTipText("Editar");
		brtnEditar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				brtnEditarActionPerformed(evt);
			}
		});

		jLabel8.setText("Código curso:");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(
										jLabel8)
								.addGap(18, 18, 18)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel4Layout.createSequentialGroup()
												.addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 87,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(39, 39, 39)
												.addComponent(brtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 89,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout
												.createSequentialGroup()
												.addComponent(jTFCodigoCurso, javax.swing.GroupLayout.PREFERRED_SIZE,
														184, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18)
												.addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 89,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(59, 59, 59)))));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(10, 10, 10)
						.addComponent(brtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(jPanel4Layout.createSequentialGroup().addGap(23, 23, 23)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTFCodigoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel8))
						.addGap(18, 18, 18).addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(20, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jPanel3,
								javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnBuscarDocenteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarDocenteActionPerformed
		// TODO add your handling code here:
		try {
			String ced = tfceduladocente.getText();
			docenteEcontrado = adminCurso.buscarDocente(ced);
			tfnombredocente.setText(docenteEcontrado.getNombre());
		} catch (ExcepcionNegocio exc) {
			JOptionPane.showMessageDialog(null, exc.getMessage());
		} catch (Exception e) {
			e.printStackTrace();
		}

	}// GEN-LAST:event_btnBuscarDocenteActionPerformed

	private void btnQuitarSesionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnQuitarSesionActionPerformed
		// TODO add your handling code here:
		try {
			int pos = tablaHorario.getSelectedRow();
			if (pos >= 0) {
				int opc = JOptionPane.showConfirmDialog(null, "Esta seguro que desea eliminar esta sesión");
				if (opc == 0) {
					cursoActual.getSesiones().remove(pos);
					adminCurso.eliminarSesionCurso(cursoActual);
					llenarTablaSesionCurso();
					JOptionPane.showMessageDialog(null, "Se eliminó la sesión");
				}
			} else {
				JOptionPane.showMessageDialog(null, "debe seleccionar una sesión de la tabla");
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}// GEN-LAST:event_btnQuitarSesionActionPerformed

	private void btnBuscarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		try {
			String cod = tfcodigoasignatura.getText();
			asigBuscada = adminCurso.buscarAsignatura(cod);

			if (asigBuscada != null) {
				tfnombreasignatura.setText(asigBuscada.getNombre());
			} else {
				JOptionPane.showMessageDialog(null, "Esta asignatura no existe");
			}
		} catch (Exception e) {
			e.printStackTrace();
		}

	}// GEN-LAST:event_btnBuscarAsignaturaActionPerformed

	private void btnAgregarSesionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAgregarSesionActionPerformed
		// TODO add your handling code here:
		try {
			DiaEnum dia = (DiaEnum) comboDia.getSelectedItem();
			int horaInicio = Integer.parseInt((String) comboHoraInicio.getSelectedItem());
			int horaFin = Integer.parseInt((String) comboHoraFin.getSelectedItem());
			if (cursoActual == null) {
				JOptionPane.showMessageDialog(null, "Debe haber buscado o creado previamente un curso");
			} else {
				SesionCurso sesion = new SesionCurso(cursoActual, dia, horaInicio, horaFin);
				adminCurso.crearSesionCurso(sesion);
				cursoActual.getSesiones().add(sesion);
				llenarTablaSesionCurso();
				JOptionPane.showMessageDialog(null, "Se creó la sesión");
			}
		} catch (ExcepcionNegocio exc) {
			JOptionPane.showMessageDialog(null, exc.getMessage());
		} catch (Exception e) {
			e.printStackTrace();
		}

	}// GEN-LAST:event_btnAgregarSesionActionPerformed

	private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarActionPerformed
		// TODO add your handling code here:
		try {
			String cod = jTFCodigoCurso.getText();
			Curso c = adminCurso.buscarCurso(cod);
			cursoActual = c;
			if (c != null) {
				tfceduladocente.setText(c.getProfesor().getCedula());
				tfnombredocente.setText(c.getProfesor().getNombre());
				tfnombreasignatura.setText(c.getAsignatura().getNombre());
				tfcodigoasignatura.setText(c.getAsignatura().getCodigo());
				llenarTablaSesionCurso();
			} else {
				JOptionPane.showMessageDialog(null, "Este curso no se encuentra registrado");
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}// GEN-LAST:event_btnBuscarActionPerformed

	private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCrearActionPerformed
		// TODO add your handling code here:
		try {
			String cod = jTFCodigoCurso.getText();
			if (docenteEcontrado != null && asigBuscada != null) {
				Curso c = new Curso(cod, docenteEcontrado, asigBuscada);
				cursoActual = c;
				adminCurso.crearCurso(c);
				JOptionPane.showMessageDialog(null, "Se creó un curso");
			} else {
				JOptionPane.showMessageDialog(null, "Se debió haber buscado previamente un docente y una asignatura");
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}// GEN-LAST:event_btnCrearActionPerformed

	private void brtnEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_brtnEditarActionPerformed
		// TODO add your handling code here:
		try {
			if (asigBuscada == null || docenteEcontrado == null || jTFCodigoCurso.getText().isEmpty()) {
				JOptionPane.showMessageDialog(null, "Debe buscar la asignatura, el docente y llenar el código");
			} else {
				if (cursoActual == null) {
					JOptionPane.showMessageDialog(null, "Debe buscar un curso antes de editar");
				} else {
					cursoActual.setAsignatura(asigBuscada);
					cursoActual.setProfesor(docenteEcontrado);
					cursoActual.setCodigo(jTFCodigoCurso.getText());
					adminCurso.editarCurso(cursoActual);
					JOptionPane.showMessageDialog(null, "Se editó el curso");
				}
			}
		} catch (ExcepcionNegocio exc) {
			JOptionPane.showMessageDialog(null, exc.getMessage());
		} catch (Exception e) {
			e.printStackTrace();
		}
	}// GEN-LAST:event_brtnEditarActionPerformed

	/**
	 * llena la tabla de sesiones de un curso
	 */
	private void llenarTablaSesionCurso() {
		DefaultTableModel dtm = (DefaultTableModel) tablaHorario.getModel();
		dtm.setRowCount(0);
		List<SesionCurso> sesiones = cursoActual.getSesiones();
		for (SesionCurso sesionCurso : sesiones) {
			dtm.addRow(new Object[] { sesionCurso.getDia(), sesionCurso.getHoraInicio(), sesionCurso.getHoraFinal() });
		}
	}

	/**
	 * Llena el combo día de la ventana
	 */
	private void llenarComboDia() {
		comboDia.addItem(DiaEnum.LUNES);
		comboDia.addItem(DiaEnum.MARTES);
		comboDia.addItem(DiaEnum.MIERCOLES);
		comboDia.addItem(DiaEnum.JUEVES);
		comboDia.addItem(DiaEnum.VIERNES);
		comboDia.addItem(DiaEnum.SABADO);
		comboDia.addItem(DiaEnum.DOMINGO);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton brtnEditar;
	private javax.swing.JButton btnAgregarSesion;
	private javax.swing.JButton btnBuscar;
	private javax.swing.JButton btnBuscarAsignatura;
	private javax.swing.JButton btnBuscarDocente;
	private javax.swing.JButton btnCrear;
	private javax.swing.JButton btnQuitarSesion;
	private javax.swing.JComboBox comboDia;
	private javax.swing.JComboBox comboHoraFin;
	private javax.swing.JComboBox comboHoraInicio;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField jTFCodigoCurso;
	private javax.swing.JTable tablaHorario;
	private javax.swing.JTextField tfceduladocente;
	private javax.swing.JTextField tfcodigoasignatura;
	private javax.swing.JTextField tfnombreasignatura;
	private javax.swing.JTextField tfnombredocente;
	// End of variables declaration//GEN-END:variables
}
