/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.disenosoft.universidad.vista.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.util.List;

import javax.swing.JOptionPane;

import co.edu.eam.disenosoft.universidad.vista.controladores.ControladorAdministrarProfesor;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.dao.definiciones.IDAOProfesor;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.Profesion;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.Profesor;

/**
 *
 * @author dir_software
 */
public class VentanaProfesor extends javax.swing.JInternalFrame implements ActionListener {

	private ControladorAdministrarProfesor adminProf;

	/**
	 * Creates new form VentanaCrearProfesor
	 */
	public VentanaProfesor() {

		adminProf = new ControladorAdministrarProfesor();
		initComponents();
		setVisible(true);
		setMaximizable(false);
		setIconifiable(true);
		setResizable(false);
		setClosable(true);
		btnCrear.addActionListener(this);
		btnBuscar.addActionListener(this);
		btnEditar.addActionListener(this);
		btnEliminar.addActionListener(this);
		refrescarCombo();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		tfTelefono = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		tfDireccion = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		tfNombre = new javax.swing.JTextField();
		tfCEdula = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		tfCorreo = new javax.swing.JTextField();
		tfApellido = new javax.swing.JTextField();
		cbProfesion = new javax.swing.JComboBox();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		checkPostgrado = new javax.swing.JCheckBox();
		jPanel2 = new javax.swing.JPanel();
		btnCrear = new javax.swing.JButton();
		btnBuscar = new javax.swing.JButton();
		btnEditar = new javax.swing.JButton();
		btnEliminar = new javax.swing.JButton();

		setIconifiable(true);
		setTitle("Administrar Profesorado");
		setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/teacher4.png"))); // NOI18N

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales"));

		jLabel6.setText("Telefono");

		jLabel2.setText("Nombre");

		jLabel1.setText("Cedula");

		jLabel5.setText("Direccion");

		jLabel4.setText("Correo Electronico");

		jLabel3.setText("Apellido");

		jLabel7.setText("Profesion");

		jLabel8.setText("Postgrado");

		checkPostgrado.setText("Si");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jLabel5)
										.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1,
												Short.MAX_VALUE)
										.addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 105,
												Short.MAX_VALUE))
								.addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 105,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addComponent(jLabel8))
						.addPreferredGap(
								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(
										checkPostgrado)
								.addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(tfCEdula).addComponent(tfNombre).addComponent(tfApellido)
										.addComponent(tfCorreo).addComponent(tfDireccion).addComponent(tfTelefono)
										.addComponent(cbProfesion, 0, 244, Short.MAX_VALUE)))
						.addContainerGap(75, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(tfCEdula, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel1))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel2))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel5).addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel6).addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(cbProfesion, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel7))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel8).addComponent(checkPostgrado))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculation1.png"))); // NOI18N

		btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N

		btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pen38.png"))); // NOI18N
		btnEditar.setEnabled(false);

		btnEliminar.setText("Eliminar");
		btnEliminar.setEnabled(false);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
						.addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 87,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 95,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 89,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18).addComponent(btnEliminar).addContainerGap(35, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup().addGap(31, 31, 31)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(33, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(15, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents
		// Variables declaration - do not modify//GEN-BEGIN:variables

	private javax.swing.JButton btnBuscar;
	private javax.swing.JButton btnCrear;
	private javax.swing.JButton btnEditar;
	private javax.swing.JButton btnEliminar;
	private javax.swing.JComboBox cbProfesion;
	private javax.swing.JCheckBox checkPostgrado;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JTextField tfApellido;
	private javax.swing.JTextField tfCEdula;
	private javax.swing.JTextField tfCorreo;
	private javax.swing.JTextField tfDireccion;
	private javax.swing.JTextField tfNombre;
	private javax.swing.JTextField tfTelefono;
	// End of variables declaration//GEN-END:variables

	/**
	 * Adminstra los eventos de acción realizados en los botones de administrar
	 * docente
	 */
	public void actionPerformed(ActionEvent arg0) {

		if (arg0.getSource() == btnCrear) {

			try {
				Profesor docente = new Profesor();

				docente.setCedula(tfCEdula.getText());
				docente.setNombre(tfNombre.getText());
				docente.setApellido(tfApellido.getText());
				docente.setDireccion(tfDireccion.getText());
				docente.setTelefono(tfTelefono.getText());
				docente.setCorreo(tfCorreo.getText());
				docente.setProfesion((Profesion) cbProfesion.getSelectedItem());

				int index = cbProfesion.getSelectedIndex();
				boolean postgrado;
				if (checkPostgrado.isSelected()) {
					postgrado = true;
				} else {
					postgrado = false;
				}
				docente.setPostgrado(postgrado);

				if (index == 0) {
					JOptionPane.showMessageDialog(null, "Debe seleccionar un tipo de profesión");
				} else {
					adminProf.crear(docente);
					JOptionPane.showMessageDialog(null, "El docente ha sido registrado");
				}

			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

		}

		if (arg0.getSource() == btnBuscar) {

			try {

				String ced = tfCEdula.getText();

				Profesor p = adminProf.buscar(ced);

				if (p != null) {
					tfCEdula.setText(p.getCedula());
					tfApellido.setText(p.getApellido());
					tfCorreo.setText(p.getCorreo());
					tfDireccion.setText(p.getDireccion());
					tfNombre.setText(p.getNombre());
					tfTelefono.setText(p.getTelefono());
					cbProfesion.setSelectedItem(p.getProfesion());

					btnEditar.setEnabled(true);
					btnEliminar.setEnabled(true);

					if (p.isPostgrado() == true) {
						checkPostgrado.setSelected(true);
					} else {
						checkPostgrado.setSelected(false);
					}
				} else {
					JOptionPane.showMessageDialog(null, "Este docente no se encuentra registrado");
				}

			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

		}

		if (arg0.getSource() == btnEditar) {

			try {

				String nombre = tfNombre.getText();
				String ape = tfApellido.getText();
				String ced = tfCEdula.getText();
				String dir = tfDireccion.getText();
				String tel = tfTelefono.getText();
				String email = tfCorreo.getText();
				String prof = (String) cbProfesion.getSelectedItem();

				Profesion profesion = adminProf.buscarNombre(prof);

				boolean post = false;

				if (checkPostgrado.isSelected()) {
					post = true;
				} else {
					post = false;
				}

				Profesor p = new Profesor(ced, ape, email, dir, nombre, tel, post, profesion);

				adminProf.editar(p);

				JOptionPane.showMessageDialog(null, "Se actualizó correctamente");

				btnEditar.setEnabled(false);

			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

		}

		if (arg0.getSource() == btnEliminar) {

			try {

				String cedula = tfCEdula.getText();
				if (!tfCEdula.getText().isEmpty()) {
					int res = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea eliminar este registro?");
					if (res == 0) {
						adminProf.eliminar(cedula);
						JOptionPane.showMessageDialog(null, "Eliminación exitosa!!!");
						btnEliminar.setEnabled(false);
					}

				} else {
					JOptionPane.showMessageDialog(null, "debe ingresar un número de cédula");
				}
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

		}

	}

	/**
	 * Permite agregar la lista de profesiones registradas en la BD en el combo
	 * de profesión
	 */
	public void refrescarCombo() {

		try {
			List<Profesion> lista = adminProf.listar();

			cbProfesion.removeAllItems();
			cbProfesion.addItem("Seleccione una opción");

			for (int i = 0; i < lista.size(); i++) {

				cbProfesion.addItem(lista.get(i));

			}

		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

}
