/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.disenosoft.universidad.vista.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;

import javax.swing.JOptionPane;

import co.edu.eam.disenosoft.universidad.vista.controladores.ControladorAdministarEstudiante;
import co.edu.eam.ingesoft.desarrollo.logica.excepcion.ExcepcionNegocio;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.dao.definiciones.IDAOEstudiante;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.dao.implementacion.jpa.DAOEstudianteJPA;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.Estudiante;

/**
 * 
 * @author dir_software
 */
public class VentanaAdminEstudiante extends javax.swing.JInternalFrame implements ActionListener {

	private ControladorAdministarEstudiante adminEstudiante;

	/**
	 * Creates new form VentanaAdminEstudiante
	 */
	public VentanaAdminEstudiante() {
		adminEstudiante = new ControladorAdministarEstudiante();
		initComponents();
		setVisible(true);
		setMaximizable(false);
		setIconifiable(true);
		setClosable(true);
		setResizable(false);
		btnCrear.addActionListener(this);
		btnBuscar.addActionListener(this);
		brtnEditar.addActionListener(this);
		btnEliminar.addActionListener(this);
		btnEliminar.setEnabled(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		tfTelefono = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		tfDireccion = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		tfNombre = new javax.swing.JTextField();
		tfCEdula = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		tfCorreo = new javax.swing.JTextField();
		tfApellido = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		jDFechaNaci = new com.toedter.calendar.JDateChooser();
		jPanel2 = new javax.swing.JPanel();
		btnCrear = new javax.swing.JButton();
		btnBuscar = new javax.swing.JButton();
		brtnEditar = new javax.swing.JButton();
		btnEliminar = new javax.swing.JButton();

		setMaximizable(true);
		setResizable(true);
		setTitle("Administrar Estudiantes");
		setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/student6.png"))); // NOI18N

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales"));

		jLabel6.setText("Telefono");

		jLabel2.setText("Nombre");

		jLabel1.setText("Cedula");

		jLabel5.setText("Direccion");

		jLabel4.setText("Correo Electronico");

		jLabel3.setText("Apellido");

		jLabel7.setText("Fecha De Nacimiento :");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addGroup(jPanel1Layout
								.createSequentialGroup().addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
												jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE,
																75, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGap(34, 34, 34))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
												jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel5)
														.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE,
																105, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel6))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
								.addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(tfCEdula).addComponent(tfNombre).addComponent(tfApellido)
										.addComponent(tfCorreo).addComponent(tfDireccion).addComponent(tfTelefono,
												javax.swing.GroupLayout.PREFERRED_SIZE, 244,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel7)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jDFechaNaci, javax.swing.GroupLayout.PREFERRED_SIZE, 159,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(20, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(tfCEdula, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel1))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel2))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel5).addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel6).addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jLabel7).addComponent(jDFechaNaci, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(25, Short.MAX_VALUE)));

		jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculation1.png"))); // NOI18N

		btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N

		brtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pen38.png"))); // NOI18N
		brtnEditar.setEnabled(false);

		btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete1600.png"))); // NOI18N
		btnEliminar.setEnabled(false);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(47, 47, 47)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
								.addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
								.addComponent(brtnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
								.addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap(40, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
						.addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18).addComponent(btnBuscar).addGap(18, 18, 18)
						.addComponent(brtnEditar).addGap(18, 18, 18).addComponent(btnEliminar,
								javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(32, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(22, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 19, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton brtnEditar;
	private javax.swing.JButton btnBuscar;
	private javax.swing.JButton btnCrear;
	private javax.swing.JButton btnEliminar;
	private com.toedter.calendar.JDateChooser jDFechaNaci;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JTextField tfApellido;
	private javax.swing.JTextField tfCEdula;
	private javax.swing.JTextField tfCorreo;
	private javax.swing.JTextField tfDireccion;
	private javax.swing.JTextField tfNombre;
	private javax.swing.JTextField tfTelefono;
	// End of variables declaration//GEN-END:variables

	public void actionPerformed(ActionEvent arg0) {

		if (arg0.getSource() == btnBuscar) {

			try {
				String ced = tfCEdula.getText();
				Estudiante estu = adminEstudiante.buscar(ced);

				tfApellido.setText(estu.getApellido());
				tfCEdula.setText(estu.getCedula());
				tfDireccion.setText(estu.getDireccion());
				tfCorreo.setText(estu.getCorreo());
				tfNombre.setText(estu.getNombre());
				tfTelefono.setText(estu.getTelefono());
				jDFechaNaci.setDate(estu.getFechaNacimiento());

				brtnEditar.setEnabled(true);
				btnEliminar.setEnabled(true);

			} catch (ExcepcionNegocio exc) {
				JOptionPane.showMessageDialog(null, exc.getMessage());
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

		}

		if (arg0.getSource() == btnCrear) {

			try {

				String ced = tfCEdula.getText();
				String ape = tfApellido.getText();
				String email = tfCorreo.getText();
				String dir = tfDireccion.getText();
				String nom = tfNombre.getText();
				String tel = tfTelefono.getText();
				Date fecha = jDFechaNaci.getDate();

				Estudiante estu = new Estudiante(ced, ape, email, dir, nom, tel, fecha);

				adminEstudiante.crear(estu);
				JOptionPane.showMessageDialog(null, "Creado!!!");

			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

		}

		if (arg0.getSource() == brtnEditar) {

			try {

				String ced = tfCEdula.getText();
				String ape = tfApellido.getText();
				String email = tfCorreo.getText();
				String dir = tfDireccion.getText();
				String nom = tfNombre.getText();
				String tel = tfTelefono.getText();
				Date fecha = jDFechaNaci.getDate();

				Estudiante estu = new Estudiante(ced, ape, email, dir, nom, tel, fecha);
				adminEstudiante.editar(estu);

				JOptionPane.showMessageDialog(null, "Se editó correctamente");
				brtnEditar.setEnabled(false);

			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

		}

		if (arg0.getSource() == btnEliminar) {

			try {

				String ced = tfCEdula.getText();

				adminEstudiante.eliminar(ced);

				JOptionPane.showMessageDialog(null, "Se eliminó correctamente");

				brtnEditar.setEnabled(false);
				btnEliminar.setEnabled(false);

			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

		}

	}
}
