/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.disenosoft.universidad.vista.gui;

import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import co.edu.eam.disenosoft.universidad.vista.controladores.ControladorAdministrarCurso;
import co.edu.eam.disenosoft.universidad.vista.controladores.ControladorRegistrarCurso;
import co.edu.eam.ingesoft.desarrollo.logica.excepcion.ExcepcionNegocio;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.Asignatura;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.Curso;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.Estudiante;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.RegistroCurso;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.SesionCurso;

/**
 *
 * @author dir_software
 */
public class VentanaRegistrarCurso extends javax.swing.JInternalFrame {

	private ControladorRegistrarCurso adminRegistroCurso;
	private ControladorAdministrarCurso adminCurso;
	private Estudiante estudianteEncontrado;
	private Asignatura asignEncontrada;

	/**
	 * Creates new form VentanaRegistrarCurso
	 */
	public VentanaRegistrarCurso() {
		adminRegistroCurso = new ControladorRegistrarCurso();
		estudianteEncontrado = null;
		asignEncontrada = null;
		adminCurso = new ControladorAdministrarCurso();
		initComponents();
		setVisible(true);
		setMaximizable(false);
		setIconifiable(true);
		setResizable(false);
		setClosable(true);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		tfcodigoasignatura = new javax.swing.JTextField();
		btnBuscarAsignatura = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		tfnombreasignatura = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		tablaHorario = new javax.swing.JTable();
		jLabel5 = new javax.swing.JLabel();
		tfcreditosasignatura = new javax.swing.JTextField();
		btnRegistrarAsignatura = new javax.swing.JButton();
		jLabel7 = new javax.swing.JLabel();
		jtfTipo = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		tfcedulaestudiante = new javax.swing.JTextField();
		btnBuscarEstudiante = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		tfnombreestudiante = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		tfcreditosregistradosestudiante = new javax.swing.JTextField();

		setIconifiable(true);
		setTitle("Registrar Curso");
		setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/abc1.png"))); // NOI18N

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Asignatura"));

		jLabel1.setText("Codigo");

		btnBuscarAsignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
		btnBuscarAsignatura.setToolTipText("Buscar Asignatura");
		btnBuscarAsignatura.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBuscarAsignaturaActionPerformed(evt);
			}
		});

		jLabel2.setText("Nombre");

		tfnombreasignatura.setEditable(false);

		jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cursos Asignatura"));

		tablaHorario.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null }, { null, null }, { null, null }, { null, null } },
				new String[] { "Codigo", "Horario" }));
		jScrollPane1.setViewportView(tablaHorario);

		jLabel5.setText("Creditos");

		tfcreditosasignatura.setEditable(false);

		btnRegistrarAsignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculation1.png"))); // NOI18N
		btnRegistrarAsignatura.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnRegistrarAsignaturaActionPerformed(evt);
			}
		});

		jLabel7.setText("Tipo:");

		jtfTipo.setEditable(false);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(
						jPanel1Layout
								.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444,
												Short.MAX_VALUE)
										.addGroup(jPanel1Layout
												.createSequentialGroup().addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(jPanel1Layout.createSequentialGroup().addGroup(
																jPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(jLabel2).addComponent(jLabel1)
																		.addComponent(jLabel5))
																.addGap(25, 25, 25)
																.addGroup(jPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																		.addGroup(jPanel1Layout.createSequentialGroup()
																				.addComponent(tfcreditosasignatura,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						58,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																				.addComponent(jLabel7)
																				.addGap(35, 35, 35)
																				.addComponent(jtfTipo,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						132, Short.MAX_VALUE))
																		.addComponent(tfnombreasignatura,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				259, Short.MAX_VALUE)
																		.addComponent(tfcodigoasignatura))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(btnBuscarAsignatura))
														.addComponent(btnRegistrarAsignatura))
												.addGap(0, 0, Short.MAX_VALUE)))
										.addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(
								jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												jPanel1Layout.createSequentialGroup()
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(jLabel1).addComponent(tfcodigoasignatura,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(jLabel2).addComponent(tfnombreasignatura,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 51,
												javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel5)
								.addComponent(tfcreditosasignatura, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel7).addComponent(jtfTipo, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(btnRegistrarAsignatura)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Estudiante"));

		jLabel3.setText("Cedula");

		btnBuscarEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
		btnBuscarEstudiante.setToolTipText("Buscar Docente");
		btnBuscarEstudiante.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBuscarEstudianteActionPerformed(evt);
			}
		});

		jLabel4.setText("Nombre");

		tfnombreestudiante.setEditable(false);

		jLabel6.setText("Creditos Registrados");

		tfcreditosregistradosestudiante.setEditable(false);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel6).addComponent(jLabel4).addComponent(jLabel3))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(tfcedulaestudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 259,
										Short.MAX_VALUE)
								.addComponent(tfnombreestudiante).addComponent(tfcreditosregistradosestudiante))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(btnBuscarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 65,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
						.addComponent(btnBuscarEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel3).addComponent(tfcedulaestudiante,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(5, 5, 5)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel4).addComponent(tfnombreestudiante,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel6).addComponent(tfcreditosregistradosestudiante,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(
										jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup()
										.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(0, 0, Short.MAX_VALUE)))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnRegistrarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRegistrarAsignaturaActionPerformed
		// TODO add your handling code here:
		try {
			int pos = tablaHorario.getSelectedRow();
			if (pos >= 0) {
				DefaultTableModel dtm = (DefaultTableModel) tablaHorario.getModel();
				String cod = (String) dtm.getValueAt(pos, 0);
				Curso c = adminCurso.buscarCurso(cod);
				if (estudianteEncontrado != null && c != null) {
					RegistroCurso reg = new RegistroCurso(estudianteEncontrado, c);
					adminRegistroCurso.crearRegistroCurso(reg);
					JOptionPane.showMessageDialog(null, "Se registró un curso");
				} else {
					JOptionPane.showMessageDialog(null,
							"Se debió buscar un estudiante y seleccionado un curso previamente");
				}
			} else {
				JOptionPane.showMessageDialog(null, "Debe seleccionar un objeto de la tabla");
			}
		} catch (ExcepcionNegocio exc) {
			JOptionPane.showMessageDialog(null, exc.getMessage());
		} catch (Exception e) {
			e.printStackTrace();
		}
	}// GEN-LAST:event_btnRegistrarAsignaturaActionPerformed

	private void btnBuscarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarEstudianteActionPerformed
		// TODO add your handling code here:
		try {
			String ced = tfcedulaestudiante.getText();
			Estudiante es = adminRegistroCurso.buscarEstudiante(ced);
			estudianteEncontrado = es;
			int creditos = adminRegistroCurso.creditosRegistradosEstudiante(es);
			tfnombreestudiante.setText(es.getNombre());
			tfcreditosregistradosestudiante.setText(creditos + "");
		} catch (ExcepcionNegocio exc) {
			JOptionPane.showMessageDialog(null, exc.getMessage());
		} catch (Exception e) {
			e.printStackTrace();
		}
	}// GEN-LAST:event_btnBuscarEstudianteActionPerformed

	private void btnBuscarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarAsignaturaActionPerformed
		// TODO add your handling code here:
		try {
			String cod = tfcodigoasignatura.getText();
			Asignatura as = adminRegistroCurso.buscarAsignatura(cod);
			asignEncontrada = as;
				tfnombreasignatura.setText(as.getNombre());
				tfcreditosasignatura.setText(as.getNumeroCreditos() + "");
				jtfTipo.setText(as.getTipo() + "");
				llenarTablaSesionCurso();
		} catch (ExcepcionNegocio exc){
			JOptionPane.showMessageDialog(null, exc.getMessage());
		}
		catch (Exception e) {
			e.printStackTrace();
		}
	}// GEN-LAST:event_btnBuscarAsignaturaActionPerformed

	private void llenarTablaSesionCurso() {
		try {
			DefaultTableModel dtm = (DefaultTableModel) tablaHorario.getModel();
			dtm.setRowCount(0);
			List<Curso> cursos = adminRegistroCurso.cursosAsignatura(asignEncontrada);
			for (Curso curso : cursos) {
				String cadena = "";
				for (int i = 0; i < curso.getSesiones().size(); i++) {
					cadena += curso.getSesiones().get(i).getDia() + " De " + curso.getSesiones().get(i).getHoraInicio()
							+ " A " + curso.getSesiones().get(i).getHoraFinal() + "  ";
				}
				dtm.addRow(new Object[] { curso.getCodigo(), cadena });
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnBuscarAsignatura;
	private javax.swing.JButton btnBuscarEstudiante;
	private javax.swing.JButton btnRegistrarAsignatura;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField jtfTipo;
	private javax.swing.JTable tablaHorario;
	private javax.swing.JTextField tfcedulaestudiante;
	private javax.swing.JTextField tfcodigoasignatura;
	private javax.swing.JTextField tfcreditosasignatura;
	private javax.swing.JTextField tfcreditosregistradosestudiante;
	private javax.swing.JTextField tfnombreasignatura;
	private javax.swing.JTextField tfnombreestudiante;
	// End of variables declaration//GEN-END:variables
}
