/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.disenosoft.universidad.vista.gui;

import java.awt.JobAttributes;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import co.edu.eam.disenosoft.universidad.vista.controladores.ControladorVentanaVerCurso;
import co.edu.eam.ingesoft.desarrollo.logica.excepcion.ExcepcionNegocio;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.Asignatura;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.Curso;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.Estudiante;

/**
 *
 * @author dir_software
 */
public class VentanaVerCurso extends javax.swing.JInternalFrame {

	private ControladorVentanaVerCurso adminVerCurso;
	private Asignatura asignBuscada;

	/**
	 * Creates new form VentanaVerCurso
	 */
	public VentanaVerCurso() {
		adminVerCurso = new ControladorVentanaVerCurso();
		asignBuscada = null;
		initComponents();
		refrescarCombo();
		setVisible(true);
		setMaximizable(false);
		setIconifiable(true);
		setResizable(false);
		setClosable(true);
		setClosable(true);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		tablaEstudiantes = new javax.swing.JTable();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		tfcodigoasignatura = new javax.swing.JTextField();
		btnBuscarAsignatura = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		tfnombreasignatura = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		comboCursos = new javax.swing.JComboBox();
		jLabel4 = new javax.swing.JLabel();
		btnVerEstudiante = new javax.swing.JButton();

		setTitle("Ver Curso");
		setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/classroom.png"))); // NOI18N

		tablaEstudiantes
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Cedula", "Nombre", "Apellido", "Edad" }));
		jScrollPane1.setViewportView(tablaEstudiantes);

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Asignatura"));

		jLabel1.setText("Codigo");

		btnBuscarAsignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
		btnBuscarAsignatura.setToolTipText("Buscar Asignatura");
		btnBuscarAsignatura.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBuscarAsignaturaActionPerformed(evt);
			}
		});

		jLabel2.setText("Nombre");

		tfnombreasignatura.setEditable(false);

		jLabel3.setText("Curso");

		comboCursos.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				comboCursosItemStateChanged(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(
						jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout
										.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel1)
														.addGap(37, 37, 37).addComponent(tfcodigoasignatura,
																javax.swing.GroupLayout.PREFERRED_SIZE, 231,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(jPanel1Layout
														.createSequentialGroup()
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel2).addComponent(jLabel3))
														.addGap(33, 33, 33)
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(tfnombreasignatura)
																.addComponent(comboCursos, 0,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE))))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 88,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(5, 5, 5).addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel1).addComponent(tfcodigoasignatura,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(tfnombreasignatura, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel2))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel3).addComponent(comboCursos,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addContainerGap(29, Short.MAX_VALUE)));

		jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/classroom.png"))); // NOI18N

		btnVerEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/student6.png"))); // NOI18N
		btnVerEstudiante.setToolTipText("Ver Estudiante");
		btnVerEstudiante.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnVerEstudianteActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addGroup(layout.createSequentialGroup()
								.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addComponent(jScrollPane1)).addComponent(btnVerEstudiante))
				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(15, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGap(18, 18, 18)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(btnVerEstudiante).addGap(25, 25, 25)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void comboCursosItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_comboCursosItemStateChanged
		// TODO add your handling code here:
		if (comboCursos.getSelectedIndex() != 0) {
			Curso c = (Curso) comboCursos.getSelectedItem();
			refrescarTabla(c);
		}
	}// GEN-LAST:event_comboCursosItemStateChanged

	private void btnBuscarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarAsignaturaActionPerformed
		// TODO add your handling code here:
		try {
			String cod = tfcodigoasignatura.getText();
			Asignatura a = adminVerCurso.buscarAsignatura(cod);
			asignBuscada = a;
			tfnombreasignatura.setText(a.getNombre());
			refrescarCombo();
		} catch (ExcepcionNegocio exc) {
			JOptionPane.showMessageDialog(null, exc.getMessage());
		} catch (Exception e) {
			e.printStackTrace();
		}
	}// GEN-LAST:event_btnBuscarAsignaturaActionPerformed

	private void btnVerEstudianteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnVerEstudianteActionPerformed
		// TODO add your handling code here:
		try {
			int fila = tablaEstudiantes.getSelectedRow();
			if (fila >= 0) {
				DefaultTableModel tabla = (DefaultTableModel) tablaEstudiantes.getModel();
				String ced = (String) tabla.getValueAt(fila, 0);
				Estudiante e = adminVerCurso.buscarEstudiante(ced);
				new DialogoVerEstudiante(e);
			} else {
				JOptionPane.showMessageDialog(null, "Debe seleccionar un estudiante de la tabla");
			}
		} catch (ExcepcionNegocio e) {
			JOptionPane.showMessageDialog(null, e.getMessage());
		} catch (Exception exc) {
			exc.printStackTrace();
		}
	}// GEN-LAST:event_btnVerEstudianteActionPerformed

	private void refrescarCombo() {
		try {
			List<Curso> lista = adminVerCurso.cursosAsignatura(asignBuscada);
			comboCursos.removeAllItems();
			comboCursos.addItem("Seleccione opción");
			for (int i = 0; i < lista.size(); i++) {
				comboCursos.addItem(lista.get(i));
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void refrescarTabla(Curso c) {
		try {
			DefaultTableModel dtm = (DefaultTableModel) tablaEstudiantes.getModel();
			dtm.setRowCount(0);
			List<Estudiante> estudiantes = adminVerCurso.estudiantesCurso(c);
			for (Estudiante lista : estudiantes) {
				int edad = adminVerCurso.calcularEdad(lista);
				dtm.addRow(new Object[] { lista.getCedula(), lista.getNombre(), lista.getApellido(), edad });
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnBuscarAsignatura;
	private javax.swing.JButton btnVerEstudiante;
	private javax.swing.JComboBox comboCursos;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tablaEstudiantes;
	private javax.swing.JTextField tfcodigoasignatura;
	private javax.swing.JTextField tfnombreasignatura;
	// End of variables declaration//GEN-END:variables
}
