/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.disenosoft.universidad.vista.gui;

import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import co.edu.eam.disenosoft.universidad.vista.controladores.ControladorIngresarCalificaciones;
import co.edu.eam.ingesoft.desarrollo.logica.excepcion.ExcepcionNegocio;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.Asignatura;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.Curso;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.Estudiante;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.Evaluacion;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.Nota;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.Profesor;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.RegistroCurso;

/**
 *
 * @author dir_software
 */
public class VentanaIngresarCalificaciones extends javax.swing.JInternalFrame {

	private ControladorIngresarCalificaciones controlador;

	/**
	 * Creates new form VentanaIngresarCalificaciones
	 */
	public VentanaIngresarCalificaciones() {
		controlador = new ControladorIngresarCalificaciones();
		initComponents();
		setVisible(true);
		setMaximizable(false);
		setIconifiable(true);
		setResizable(false);
		setClosable(true);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel2 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		tfceduladocente = new javax.swing.JTextField();
		btnBuscarDocente = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		tfnombredocente = new javax.swing.JTextField();
		jPanel1 = new javax.swing.JPanel();
		comboCurso = new javax.swing.JComboBox();
		jLabel5 = new javax.swing.JLabel();
		comboEvaluacion = new javax.swing.JComboBox();
		jLabel2 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tablaCalificaicon = new javax.swing.JTable();
		btnCalificar = new javax.swing.JButton();

		setTitle("Ingresar Calificaiones");
		setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/check44.png"))); // NOI18N

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Docente"));

		jLabel3.setText("Cedula");

		btnBuscarDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
		btnBuscarDocente.setToolTipText("Buscar Docente");
		btnBuscarDocente.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBuscarDocenteActionPerformed(evt);
			}
		});

		jLabel4.setText("Nombre");

		tfnombredocente.setEditable(false);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel3).addComponent(jLabel4))
						.addGap(25, 25, 25)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(tfceduladocente, javax.swing.GroupLayout.DEFAULT_SIZE, 230,
										Short.MAX_VALUE)
								.addComponent(tfnombredocente))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(btnBuscarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 77,
								javax.swing.GroupLayout.PREFERRED_SIZE)));
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout
						.createSequentialGroup().addGroup(jPanel2Layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(btnBuscarDocente, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(tfceduladocente, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(tfnombredocente, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel4))))
						.addGap(5, 5, 5)));

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Calificaciones"));

		comboCurso.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				comboCursoItemStateChanged(evt);
			}
		});

		jLabel5.setText("Curso");

		comboEvaluacion.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				comboEvaluacionItemStateChanged(evt);
			}
		});

		jLabel2.setText("Evaluación");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(31, 31, 31)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel2))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(comboEvaluacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(comboCurso, 0, 240, Short.MAX_VALUE))
						.addGap(74, 74, 74)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel5).addComponent(comboCurso, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(comboEvaluacion,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/check44.png"))); // NOI18N
		jLabel1.setText("jLabel1");

		jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado Estudiantes"));

		tablaCalificaicon
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Cedula", "Nombre", "Apellido", "Calificacion" }));
		jScrollPane1.setViewportView(tablaCalificaicon);

		btnCalificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pen41.png"))); // NOI18N
		btnCalificar.setToolTipText("Calificar Estudiante Seleccionado de la Tabla");
		btnCalificar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCalificarActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnCalificar))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18).addComponent(btnCalificar).addGap(42, 42, 42)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
						.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(layout.createSequentialGroup()
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel1)
						.addGroup(layout.createSequentialGroup()
								.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addGap(18, 18, 18).addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 351, Short.MAX_VALUE)
				.addGap(20, 20, 20)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void comboCursoItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_comboCursoItemStateChanged
		// TODO add your handling code here:
		Curso c = (Curso) comboCurso.getSelectedItem();
		refrescarEvaluaciones(c);
	}// GEN-LAST:event_comboCursoItemStateChanged

	private void comboEvaluacionItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_comboEvaluacionItemStateChanged
		// TODO add your handling code here:
		Curso c = (Curso) comboCurso.getSelectedItem();
		Evaluacion e = (Evaluacion) comboEvaluacion.getSelectedItem();
		refrescarTabla(c, e);
	}// GEN-LAST:event_comboEvaluacionItemStateChanged

	private void btnBuscarDocenteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarDocenteActionPerformed
		// TODO add your handling code here:
		try {
			String ced = tfceduladocente.getText();
			Profesor p = controlador.buscarDocente(ced);
			tfnombredocente.setText(p.getNombre());
			refrescarComboDocente(p);
		} catch (ExcepcionNegocio e) {
			JOptionPane.showMessageDialog(null, e.getMessage());
		} catch (Exception exc) {
			exc.printStackTrace();
		}
	}// GEN-LAST:event_btnBuscarDocenteActionPerformed

	private void btnCalificarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCalificarActionPerformed
		// TODO add your handling code here:
		try {
			int fila = tablaCalificaicon.getSelectedRow();
			if (comboCurso.getSelectedIndex() != 0) {
				if (fila >= 0) {
					String columna = (String) tablaCalificaicon.getValueAt(fila, 3);
					double valor = Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese la calificación"));
					if (valor < 0 || valor > 5) {
						JOptionPane.showMessageDialog(null, "debe ingresar notas entre 0 y 5");
					} else {
						Curso c = (Curso) comboCurso.getSelectedItem();
						List<Estudiante> estudiantes = controlador.estudiantes(c);
						Estudiante e = estudiantes.get(fila);
						RegistroCurso r = controlador.registroEstudiante(e, c);
						Evaluacion eval = (Evaluacion) comboEvaluacion.getSelectedItem();
						Nota n = new Nota(r, eval, valor, false);
						controlador.agregarNota(n, columna);
						refrescarTabla(c, eval);
					}
				} else {
					JOptionPane.showMessageDialog(null, "Debe seleccionar un estudiante de la tabla");
				}
			} else {
				JOptionPane.showMessageDialog(null, "Debe seleccionar un curso");
			}
		} catch (ExcepcionNegocio exc) {
			JOptionPane.showMessageDialog(null, exc.getMessage());
		} catch (Exception e) {
			e.printStackTrace();
		}
	}// GEN-LAST:event_btnCalificarActionPerformed

	private void refrescarComboDocente(Profesor d) {
		try {
			List<Curso> lista = controlador.cursosDocente(d);
			comboCurso.removeAllItems();
			for (int i = 0; i < lista.size(); i++) {
				comboCurso.addItem(lista.get(i));
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	private void refrescarEvaluaciones(Curso c) {
		try {
			comboEvaluacion.removeAllItems();
			List<Evaluacion> lista = c.getEvaluaciones();
			for (int i = 0; i < lista.size(); i++) {
				comboEvaluacion.addItem(lista.get(i));
			}
		} catch (NullPointerException exc) {
			JOptionPane.showMessageDialog(null, "Este curso no tiene evaluaciones");
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void refrescarTabla(Curso c, Evaluacion a) {
		try {
			DefaultTableModel dtm = (DefaultTableModel) tablaCalificaicon.getModel();
			dtm.setRowCount(0);
			List<Estudiante> estudiantes = controlador.estudiantes(c);
			for (Estudiante lista : estudiantes) {
				String calificacion = controlador.calificacionEstudiante(lista, a);
				dtm.addRow(new Object[] { lista.getCedula(), lista.getNombre(), lista.getApellido(), calificacion });
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnBuscarDocente;
	private javax.swing.JButton btnCalificar;
	private javax.swing.JComboBox comboCurso;
	private javax.swing.JComboBox comboEvaluacion;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tablaCalificaicon;
	private javax.swing.JTextField tfceduladocente;
	private javax.swing.JTextField tfnombredocente;
	// End of variables declaration//GEN-END:variables
}
